alignment_weight: 0.1
batch_size: 64
blur_kernel: 0
component_weight: 0.5
cosmology_weight: 1.0
data_root: /n/netscratch/iaifi_lab/Lab/
dropout: 0.1
epochs: 80
img_size: 256
k_samples: 15000
level_weights:
- 2.0
- 1.0
- 0.5
loss_type: multilevel
lr: 0.0003
matter_weight: 2.0
model_type: large
normalize: false
num_workers: 4
pair_type: MultiComponent
patience: 15
pretrained_path: /n/netscratch/iaifi_lab/Lab/msliu/small_net/best_cnn_model_blur_0_large.pt
temperature: 0.05
train_ratio: 0.6
use_auxiliary_classifier: false
val_ratio: 0.2
weight_decay: 0.0001
